// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_amorpm;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_year;
extern lv_obj_t * ui_status;
extern lv_obj_t * ui_batterypercent;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_GB_16);
LV_FONT_DECLARE(ui_font_GB_8);
LV_FONT_DECLARE(ui_font_GB_4);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
