// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_default_screen_init(void)
{
    ui_default = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_default, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_default, lv_color_hex(0x8BAC0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_default, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_default, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_year = lv_label_create(ui_default);
    lv_obj_set_width(ui_year, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_year, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_year, 46);
    lv_obj_set_y(ui_year, 35);
    lv_obj_set_align(ui_year, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_year, "2024");
    lv_obj_set_style_text_font(ui_year, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batterypercent = lv_label_create(ui_default);
    lv_obj_set_width(ui_batterypercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batterypercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batterypercent, 59);
    lv_obj_set_y(ui_batterypercent, -32);
    lv_obj_set_align(ui_batterypercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batterypercent, "100");
    lv_obj_set_style_text_font(ui_batterypercent, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour = lv_label_create(ui_default);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, -37);
    lv_obj_set_y(ui_hour, -15);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "32");
    lv_obj_set_style_text_font(ui_hour, &ui_font_GB_17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_colon = lv_label_create(ui_default);
    lv_obj_set_width(ui_colon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_colon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_colon, -15);
    lv_obj_set_y(ui_colon, -15);
    lv_obj_set_align(ui_colon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_colon, ":");
    lv_obj_set_style_text_font(ui_colon, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_min = lv_label_create(ui_default);
    lv_obj_set_width(ui_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_min, 6);
    lv_obj_set_y(ui_min, -15);
    lv_obj_set_align(ui_min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_min, "31");
    lv_obj_set_style_text_font(ui_min, &ui_font_GB_17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_second = lv_label_create(ui_default);
    lv_obj_set_width(ui_second, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_second, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_second, 47);
    lv_obj_set_y(ui_second, -15);
    lv_obj_set_align(ui_second, LV_ALIGN_CENTER);
    lv_label_set_text(ui_second, "25");
    lv_obj_set_style_text_font(ui_second, &ui_font_GB_17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humid = lv_label_create(ui_default);
    lv_obj_set_width(ui_humid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humid, -29);
    lv_obj_set_y(ui_humid, 13);
    lv_obj_set_align(ui_humid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humid, "humid~");
    lv_obj_set_style_text_font(ui_humid, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_label_create(ui_default);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, -33);
    lv_obj_set_y(ui_temp, 21);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "Temp~");
    lv_obj_set_style_text_font(ui_temp, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempnum = lv_label_create(ui_default);
    lv_obj_set_width(ui_tempnum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempnum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempnum, -7);
    lv_obj_set_y(ui_tempnum, 26);
    lv_obj_set_align(ui_tempnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempnum, "32\n");
    lv_obj_set_style_text_font(ui_tempnum, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidnum = lv_label_create(ui_default);
    lv_obj_set_width(ui_humidnum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidnum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidnum, 1);
    lv_obj_set_y(ui_humidnum, 13);
    lv_obj_set_align(ui_humidnum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidnum, "60");
    lv_obj_set_style_text_font(ui_humidnum, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_default);
    lv_img_set_src(ui_Image1, &ui_img_tile009_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image1, 69);
    lv_obj_set_y(ui_Image1, 29);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_default);
    lv_img_set_src(ui_Image2, &ui_img_tile009_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image2, -69);
    lv_obj_set_y(ui_Image2, 29);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_default);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 25);
    lv_obj_set_y(ui_Label1, -15);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, ":");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_default);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day, -42);
    lv_obj_set_y(ui_day, 0);
    lv_obj_set_align(ui_day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day, "mon");
    lv_obj_set_style_text_font(ui_day, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_default);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -24);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, ",");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_month = lv_label_create(ui_default);
    lv_obj_set_width(ui_month, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_month, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_month, -7);
    lv_obj_set_y(ui_month, 0);
    lv_obj_set_align(ui_month, LV_ALIGN_CENTER);
    lv_label_set_text(ui_month, "jan");
    lv_obj_set_style_text_font(ui_month, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ordinal = lv_label_create(ui_default);
    lv_obj_set_width(ui_ordinal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ordinal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ordinal, 18);
    lv_obj_set_y(ui_ordinal, 0);
    lv_obj_set_align(ui_ordinal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ordinal, "24");
    lv_obj_set_style_text_font(ui_ordinal, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_default);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 76);
    lv_obj_set_y(ui_Label6, -32);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "[");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_default);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 14);
    lv_obj_set_y(ui_Label7, 13);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "[");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_default);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 10);
    lv_obj_set_y(ui_Label8, 21);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, ")C");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status = lv_label_create(ui_default);
    lv_obj_set_width(ui_status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_status, -27);
    lv_obj_set_y(ui_status, -31);
    lv_obj_set_align(ui_status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status, "");
    lv_obj_set_style_text_font(ui_status, &ui_font_GB_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}
