// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_mainMenu_screen_init(void)
{
    ui_mainMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainMenu, lv_color_hex(0x8BAC0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batterypercent2 = lv_label_create(ui_mainMenu);
    lv_obj_set_width(ui_batterypercent2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batterypercent2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batterypercent2, 59);
    lv_obj_set_y(ui_batterypercent2, -32);
    lv_obj_set_align(ui_batterypercent2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batterypercent2, "100");
    lv_obj_set_style_text_font(ui_batterypercent2, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_mainMenu);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 76);
    lv_obj_set_y(ui_Label4, -32);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "[");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settime = lv_label_create(ui_mainMenu);
    lv_obj_set_width(ui_settime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settime, 1);
    lv_obj_set_y(ui_settime, -21);
    lv_obj_set_align(ui_settime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settime, "Set time");
    lv_obj_set_style_text_font(ui_settime, &ui_font_GB_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_check = lv_label_create(ui_mainMenu);
    lv_obj_set_width(ui_check, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_check, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_check, -39);
    lv_obj_set_y(ui_check, -21);
    lv_obj_set_align(ui_check, LV_ALIGN_CENTER);
    lv_label_set_text(ui_check, "~");
    lv_obj_set_style_text_font(ui_check, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setdate = lv_label_create(ui_mainMenu);
    lv_obj_set_width(ui_setdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setdate, 1);
    lv_obj_set_y(ui_setdate, -10);
    lv_obj_set_align(ui_setdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setdate, "Set date");
    lv_obj_set_style_text_font(ui_setdate, &ui_font_GB_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setalarm = lv_label_create(ui_mainMenu);
    lv_obj_set_width(ui_setalarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setalarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setalarm, 6);
    lv_obj_set_y(ui_setalarm, 1);
    lv_obj_set_align(ui_setalarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setalarm, "Set alarm");
    lv_obj_set_style_text_font(ui_setalarm, &ui_font_GB_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pomodoro = lv_label_create(ui_mainMenu);
    lv_obj_set_width(ui_pomodoro, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pomodoro, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pomodoro, 4);
    lv_obj_set_y(ui_pomodoro, 12);
    lv_obj_set_align(ui_pomodoro, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pomodoro, "pomodoro");
    lv_obj_set_style_text_font(ui_pomodoro, &ui_font_GB_10, LV_PART_MAIN | LV_STATE_DEFAULT);
}
