// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x8BAC0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Screen1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 1);
    lv_obj_set_y(ui_time, 17);
    lv_obj_set_align(ui_time, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_time, "32:31");
    lv_obj_set_style_text_font(ui_time, &ui_font_GB_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_amorpm = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_amorpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_amorpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_amorpm, 47);
    lv_obj_set_y(ui_amorpm, 19);
    lv_obj_set_align(ui_amorpm, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_amorpm, "AM");
    lv_obj_set_style_text_font(ui_amorpm, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, -11);
    lv_obj_set_y(ui_date, 34);
    lv_obj_set_align(ui_date, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_date, "Mon, July 8th");
    lv_obj_set_style_text_font(ui_date, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_year = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_year, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_year, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_year, 55);
    lv_obj_set_y(ui_year, 34);
    lv_obj_set_align(ui_year, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_year, "2024");
    lv_obj_set_style_text_font(ui_year, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_status, -56);
    lv_obj_set_y(ui_status, -30);
    lv_obj_set_align(ui_status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status, "charging");
    lv_obj_set_style_text_font(ui_status, &ui_font_GB_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batterypercent = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_batterypercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batterypercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batterypercent, 65);
    lv_obj_set_y(ui_batterypercent, -30);
    lv_obj_set_align(ui_batterypercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batterypercent, "100[");
    lv_obj_set_style_text_font(ui_batterypercent, &ui_font_GB_4, LV_PART_MAIN | LV_STATE_DEFAULT);

}
