// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_setTime_screen_init(void)
{
    ui_setTime = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setTime, lv_color_hex(0x8BAC0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_setTime, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batterypercent1 = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_batterypercent1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batterypercent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batterypercent1, 59);
    lv_obj_set_y(ui_batterypercent1, -32);
    lv_obj_set_align(ui_batterypercent1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batterypercent1, "100");
    lv_obj_set_style_text_font(ui_batterypercent1, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour1 = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_hour1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour1, -37);
    lv_obj_set_y(ui_hour1, 1);
    lv_obj_set_align(ui_hour1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour1, "32");
    lv_obj_set_style_text_font(ui_hour1, &ui_font_GB_17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_colon1 = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_colon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_colon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_colon1, -17);
    lv_obj_set_y(ui_colon1, 1);
    lv_obj_set_align(ui_colon1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_colon1, ":");
    lv_obj_set_style_text_font(ui_colon1, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_min1 = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_min1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_min1, 4);
    lv_obj_set_y(ui_min1, 1);
    lv_obj_set_align(ui_min1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_min1, "31");
    lv_obj_set_style_text_font(ui_min1, &ui_font_GB_17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_second1 = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_second1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_second1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_second1, 42);
    lv_obj_set_y(ui_second1, 1);
    lv_obj_set_align(ui_second1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_second1, "25");
    lv_obj_set_style_text_font(ui_second1, &ui_font_GB_17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_setTime);
    lv_img_set_src(ui_Image3, &ui_img_tile009_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image3, 69);
    lv_obj_set_y(ui_Image3, 29);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_setTime);
    lv_img_set_src(ui_Image4, &ui_img_tile009_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image4, -69);
    lv_obj_set_y(ui_Image4, 29);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 21);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, ":");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 76);
    lv_obj_set_y(ui_Label9, -32);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "[");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -38);
    lv_obj_set_y(ui_Label5, -15);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "hrs");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_GB_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 2);
    lv_obj_set_y(ui_Label10, -15);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "min");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_GB_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 41);
    lv_obj_set_y(ui_Label11, -15);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "sec");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_GB_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_setTime);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -40);
    lv_obj_set_y(ui_Label18, -31);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "set time");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_GB_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}
