// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_setDate_screen_init(void)
{
    ui_setDate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setDate, lv_color_hex(0x8BAC0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_setDate, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_year1 = lv_label_create(ui_setDate);
    lv_obj_set_width(ui_year1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_year1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_year1, 46);
    lv_obj_set_y(ui_year1, 31);
    lv_obj_set_align(ui_year1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_year1, "2024");
    lv_obj_set_style_text_font(ui_year1, &ui_font_GB_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batterypercent3 = lv_label_create(ui_setDate);
    lv_obj_set_width(ui_batterypercent3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batterypercent3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batterypercent3, 59);
    lv_obj_set_y(ui_batterypercent3, -32);
    lv_obj_set_align(ui_batterypercent3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batterypercent3, "100");
    lv_obj_set_style_text_font(ui_batterypercent3, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_setDate);
    lv_img_set_src(ui_Image5, &ui_img_tile009_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image5, 69);
    lv_obj_set_y(ui_Image5, 29);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_setDate);
    lv_img_set_src(ui_Image6, &ui_img_tile009_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image6, -69);
    lv_obj_set_y(ui_Image6, 29);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_month1 = lv_label_create(ui_setDate);
    lv_obj_set_width(ui_month1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_month1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_month1, -44);
    lv_obj_set_y(ui_month1, 1);
    lv_obj_set_align(ui_month1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_month1, "jan");
    lv_obj_set_style_text_font(ui_month1, &ui_font_GB_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ordinal1 = lv_label_create(ui_setDate);
    lv_obj_set_width(ui_ordinal1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ordinal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ordinal1, -3);
    lv_obj_set_y(ui_ordinal1, 1);
    lv_obj_set_align(ui_ordinal1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ordinal1, "24");
    lv_obj_set_style_text_font(ui_ordinal1, &ui_font_GB_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_setDate);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 76);
    lv_obj_set_y(ui_Label14, -32);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "[");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_GB_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_setDate);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -40);
    lv_obj_set_y(ui_Label20, -31);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "set date");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_GB_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}
